services:
  db:
    container_name: postgres_gestao_pessoas
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao-pessoas-db
    restart: always
    ports:
      - "5431:5432"