spring:
  application:
    name: gestao-pessoas
  datasource:
    url: jdbc:postgresql://localhost:5431/gestao-pessoas-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: public
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui/index.html